FROM registry.suse.com/bci/golang:1.25

ARG DAPPER_HOST_ARCH
ENV HOST_ARCH=${DAPPER_HOST_ARCH} ARCH=${DAPPER_HOST_ARCH}

RUN echo "no-cache"

RUN zypper -n rm container-suseconnect && \
    zypper -n install git curl docker gzip tar wget awk

## install golangci
RUN curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s v1.57.1

# The docker version in dapper is too old to have buildx. Install it manually.
RUN curl -sSfL https://github.com/docker/buildx/releases/download/v0.13.1/buildx-v0.13.1.linux-${ARCH} -o buildx-v0.13.1.linux-${ARCH} && \
    chmod +x buildx-v0.13.1.linux-${ARCH} && \
    mv buildx-v0.13.1.linux-${ARCH} /usr/local/bin/buildx

## install standard Kubernetes code generation tools
RUN go install k8s.io/code-generator/cmd/deepcopy-gen@v0.33.1
RUN go install k8s.io/code-generator/cmd/client-gen@v0.33.1
RUN go install k8s.io/code-generator/cmd/lister-gen@v0.33.1
RUN go install k8s.io/code-generator/cmd/informer-gen@v0.33.1

## install controller-gen (optional for CRD generation)
RUN go install sigs.k8s.io/controller-tools/cmd/controller-gen@v0.15.0

ENV DAPPER_ENV REPO TAG CROSS IMAGE
ENV DAPPER_SOURCE /go/src/github.com/Vicente-Cheng/mammuthus
ENV DAPPER_OUTPUT ./bin ./manifests
ENV DAPPER_DOCKER_SOCKET true
ENV HOME ${DAPPER_SOURCE}
WORKDIR ${DAPPER_SOURCE}

ENTRYPOINT ["./scripts/entry"]
CMD ["ci"]
