---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    {}
  name: nfsexports.freezeio.dev
spec:
  group: freezeio.dev
  names:
    kind: NFSExport
    listKind: NFSExportList
    plural: nfsexports
    shortNames:
    - nfsexport
    - nfsexports
    singular: nfsexport
  scope: Namespaced
  versions:
  - additionalPrinterColumns:
    - jsonPath: .spec.exportID
      name: ExportID
      type: string
    - jsonPath: .spec.exportPath
      name: Path
      type: string
    - jsonPath: .spec.exportPseudoPath
      name: PseudoPath
      type: string
    - jsonPath: .spec.nodeName
      name: Node
      type: string
    - jsonPath: .status.exportStatus
      name: Status
      type: string
    name: v1beta1
    schema:
      openAPIV3Schema:
        properties:
          apiVersion:
            description: |-
              APIVersion defines the versioned schema of this representation of an object.
              Servers should convert recognized schemas to the latest internal value, and
              may reject unrecognized values.
              More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
            type: string
          kind:
            description: |-
              Kind is a string value representing the REST resource this object represents.
              Servers may infer this from the endpoint the client submits requests to.
              Cannot be updated.
              In CamelCase.
              More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
            type: string
          metadata:
            type: object
          spec:
            description: NFSExportSpec defines the desired state of NFSExport
            properties:
              accessType:
                type: string
              enabled:
                type: boolean
              exportID:
                type: integer
              exportPath:
                type: string
              exportPseudoPath:
                type: string
              fsal:
                description: only VFS could skip the extra struct, because VFS did
                  not have any extra fields
                properties:
                  fsalType:
                    type: string
                required:
                - fsalType
                type: object
              nodeName:
                type: string
              secType:
                type: string
              squash:
                type: string
            required:
            - accessType
            - enabled
            - exportID
            - exportPath
            - exportPseudoPath
            - fsal
            - nodeName
            type: object
          status:
            properties:
              accessType:
                type: string
              exportID:
                type: integer
              exportPath:
                type: string
              exportPseudoPath:
                type: string
              exportStatus:
                type: string
              fsal:
                description: only VFS could skip the extra struct, because VFS did
                  not have any extra fields
                properties:
                  fsalType:
                    type: string
                required:
                - fsalType
                type: object
              secType:
                type: string
              squash:
                type: string
            required:
            - exportStatus
            type: object
        required:
        - spec
        type: object
    served: true
    storage: true
    subresources:
      status: {}
