#!/bin/bash
set -e

source $(dirname $0)/version

cd $(dirname $0)/..

# update ganesha source
pushd nfs-ganesha
git submodule update --init --recursive
popd

if [[ -v IMAGE ]]; then
    echo "IMAGE is set to ${IMAGE}"
else
    IMAGE=${REPO}/mammuthus-controller:${TAG}
fi
DOCKERFILE=package/Dockerfile
if [ -e ${DOCKERFILE}.${ARCH} ]; then
    DOCKERFILE=${DOCKERFILE}.${ARCH}
fi

buildx build --pull --no-cache -f ${DOCKERFILE} -t ${IMAGE} .
echo Built ${IMAGE}
