#!/bin/bash
set -e

source $(dirname $0)/version

cd $(dirname $0)/..

IMAGE=${REPO}/mammuthus-controller:${TAG}
DOCKERFILE=package/Dockerfile
if [ -e ${DOCKERFILE}.${ARCH} ]; then
    DOCKERFILE=${DOCKERFILE}.${ARCH}
fi

buildx build --pull --no-cache -f ${DOCKERFILE} -t ${IMAGE} .
echo Built ${IMAGE}
