---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    {}
  name: nfsexports.freezeio.dev
spec:
  group: freezeio.dev
  names:
    kind: NFSExport
    listKind: NFSExportList
    plural: nfsexports
    shortNames:
    - nfsexport
    - nfsexports
    singular: nfsexport
  scope: Namespaced
  versions:
  - additionalPrinterColumns:
    - jsonPath: .spec.exportID
      name: ExportID
      type: string
    - jsonPath: .spec.exportPath
      name: ExportPath
      type: string
    - jsonPath: .spec.exportPseudoPath
      name: ExportPseudoPath
      type: string
    name: v1beta1
    schema:
      openAPIV3Schema:
        properties:
          apiVersion:
            description: |-
              APIVersion defines the versioned schema of this representation of an object.
              Servers should convert recognized schemas to the latest internal value, and
              may reject unrecognized values.
              More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
            type: string
          kind:
            description: |-
              Kind is a string value representing the REST resource this object represents.
              Servers may infer this from the endpoint the client submits requests to.
              Cannot be updated.
              In CamelCase.
              More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
            type: string
          metadata:
            type: object
          spec:
            description: NFSExportSpec defines the desired state of NFSExport
            properties:
              accessType:
                type: string
              exportID:
                type: integer
              exportPath:
                type: string
              exportPseudoPath:
                type: string
              fsal:
                properties:
                  vfs:
                    properties:
                      name:
                        type: string
                    required:
                    - name
                    type: object
                type: object
              nodeID:
                type: string
            required:
            - accessType
            - exportID
            - exportPath
            - exportPseudoPath
            - nodeID
            type: object
          status:
            properties:
              exportID:
                type: integer
            required:
            - exportID
            type: object
        required:
        - spec
        type: object
    served: true
    storage: true
    subresources:
      status: {}
