apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "mammuthus-controller.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
  {{- include "mammuthus-controller.labels" . | nindent 4 }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "mammuthus-controller.name" . }}
rules:
  - apiGroups: [ "freezeio.dev" ]
    resources: [ "nfsexports", "nfsexports/status" ]
    verbs: [ "*" ]
  - apiGroups: [ "coordination.k8s.io" ]
    resources: [ "leases" ]
    verbs: [ "*" ]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "mammuthus-controller.name" . }}
  labels:
  {{- include "mammuthus-controller.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "mammuthus-controller.name" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "mammuthus-controller.name" . }}
    namespace: {{ .Release.Namespace }}
