apiVersion: v1
kind: Service
metadata:
  name: mammuthus
  namespace: {{ .Release.Namespace }}
spec:
  ports:
  - name: nfs
    port: 2049
  - name: mountd
    port: 20048
  - name: rpcbind
    port: 111
  selector:
    {{- include "mammuthus-service.selectorLabels" . | nindent 4 }}
