name: Daily Build Test

on:
  schedule:
    - cron: "0 1 * * *"

jobs:
  Daily-Test:
    uses: ./.github/workflows/factory_test.yml
    with:
      image-prefix: ttl.sh/mammuthus-controller-pr-${{ github.event.number }}
      tag: 1h
    secrets: inherit