name: Dev Build and Publish

on:
  push:
    branches:
    - main

jobs:
  Build-For-Dev:
    uses: ./.github/workflows/factory_build.yml
    with:
      tag: ${{ github.ref_name }}-head
      push: true
    secrets: inherit